django/WebDocViewer/testsite/apps/docview/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from haystack.views import SearchView, search_view_factory
import views,views_manage, views_users

urlpatterns = patterns('',
    #url(r'^$', views.index, name='index' ),
    
    url(r'^showswf/+(?P<bookid>.*?)/*$', views.getswf, name='doc_showswf' ),
    url(r'^showpdf/+(?P<bookid>.*?)/+(?P<page>\d+)/$', views.getpdf, name='doc_showpdf' ),
    url(r'^getpdfpage/+(?P<bookid>.*?)/+(?P<page>\d+)/$', views.getpdfpage, name='doc_getpdfpage' ),
    url(r'^showhtml/+(?P<bookid>.*?)/+(?P<page>\d+)/$', views.gethtml, name='doc_showhtml' ),
    url(r'^gethtmlpage/+(?P<bookid>.*?)/+(?P<page>\d+)/$', views.gethtmlpage, name='doc_gethtmlpage' ),

    url(r'^view/+(?P<bookid>.*?)/*$', views.view, name='doc_view' ),
    url(r'^directview/+(?P<path>.*)/$', views.directview, name='doc_directview' ),
    url(r'^pdfviewer/', TemplateView.as_view(template_name="pdfviewer.html") ),
    url(r'^history/*$', views.viewhistory, name='doc_viewhistory' ),

    url(r'^search/$', search_view_factory(view_class=views.BookSearchView, load_all=False, template='search/search.html', form_class=views.BookSearchForm), name='doc_search'),
    
    
    url(r'^manage/book/$', views_manage.booklist, name='doc_manage_index' ),
    url(r'^manage/bookupload/$', views_manage.upload, name='doc_manage_upload' ),
    url(r'^manage/bookedit/+(?P<bookid>.*)/$', views_manage.bookedit, name='doc_manage_bookedit' ),
    url(r'^manage/bookdelete/+(?P<bookid>.*)/$', views_manage.bookdelete, name='doc_manage_bookdelete' ),
    url(r'^manage/pdfregen/+(?P<bookid>.*)/$', views_manage.pdfregen, name='doc_manage_pdfregen' ),

    url(r'^manage/user/$', views_manage.userlist, name='user_manage_index' ),
    url(r'^manage/useredit/+(?P<userid>.*)/$', views_manage.useredit, name='manage_useredit' ),
    url(r'^manage/userdelete/+(?P<userid>.*)/$', views_manage.userdelete, name='manage_userdelete' ),


    url(r'^user/register/+(?P<regtype>.*?)/*$', views_users.register, name='user_register' ),
    url(r'^user/addfav/+(?P<bookid>.*?)/$', views_users.addfavorite, name='user_addfavorite' ),
    url(r'^user/myfavorite/$', views_users.myfavorite, name='user_myfavorite' ),
    url(r'^user/myfavorite/remove/+(?P<id>\d+)/$', views_users.removefavorite, name='user_removefavorite' ),
    url(r'^user/myspace/$', TemplateView.as_view(template_name="user/myspace.html") ),


    url(r'^login/+@*(?P<path>.*)$', views.login, name='login' ),
    url(r'^logout/$', views.logout, name='logout' ),
    
    url(r'^classview/+(?P<path>.*)$', views.classview, name='doc_classview' ),
    
    
    url(r'^test/testpdf/$', TemplateView.as_view(template_name="test.html") ),
    url(r'^test/getpdf/+(?P<bookid>.*?)/+(?P<page>\d+)/$' , views.testgetpdf, name='doc_getpdf' ),
)

django/WebDocViewer/testsite/testsite/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'testsite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^docview/', include('apps.docview.urls')),
    
    url(r'^$', 'apps.docview.views.index', name='index' ),
)

django/WebDocViewer/testsite/apps/docview/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.conf import settings
import sys
import os

from sqlalchemy import Table, Column, Integer, String, ForeignKey, MetaData
from sqlalchemy.orm import mapper
from apps.backends.DBEnginee.djSQLAlchemy import metadata
# Create your models here.

class Book(models.Model):
    bookid  =models.CharField(u'bookid',max_length=250,blank=False)
    name    =models.CharField(u'名称',max_length=250,blank=False)
    author  =models.CharField(u'作者',max_length=200,blank=True)
    descr    =models.CharField(u'简介',max_length=500,blank=True)
    tags    =models.CharField(u'标签',max_length=200,blank=True)
    summary =models.CharField(u'摘要',max_length=2048,blank=True)
    path    =models.CharField(u'路径',max_length=500,blank=True)
    format  =models.CharField(u'格式',max_length=10,blank=True)
    uploadtime  =models.CharField(u'上传时间',max_length=20,blank=True)
    uploader    =models.CharField(u'上传人',max_length=50,blank=True)
    flag        =models.IntegerField(u'上传人',max_length=50,blank=True)
    cost        =models.IntegerField(u'上传人',max_length=50,blank=True)
    counter    =models.IntegerField(u'上传人',max_length=50,blank=True)
    def __unicode__(self):
        return self.name.encode(sys.stdin.encoding)
        
    class Meta:
        db_table = 'b_book'

DocImages = {
    'pdf' : 'pdf.png',
    'doc' : 'word.png',
    'docx' : 'word.png',
    'xls' : 'excel.png',
    'xlsx' : 'excel.png',
    'ppt' : 'ppt.png',
    'pptx' : 'ppt.png',
    'other' : 'other.png',
}

#sqlalchemy book
Book_table=Table("b_book", metadata, autoload=True)
class BookSL(object):
    def getImage(self):
        format = (self.format or os.path.splitext(self.path or self.name)[1][1:]  or 'other').lower()
        jpg = DocImages.get(format , DocImages['other'])
        return '/static/image/' + jpg
        
mapper(BookSL, Book_table)  

#sqlalchemy book
User_table=Table("b_user", metadata, autoload=True)
class UserSL(object):
    pass
mapper(UserSL, User_table)  
  

UserBook_table=Table("b_user_book", metadata, autoload=True)
class UserBookSL(object):
    pass
mapper(UserBookSL, UserBook_table)  
  
  

django/WebDocViewer/testsite/apps/docview/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from django.shortcuts import render, redirect,render_to_response
from django.http import HttpResponse
from django.template import RequestContext
from django.conf import settings
from django.http import HttpResponseRedirect
from django import forms
from django.utils.encoding import force_text
from apps.backends.DBEnginee.djSQLAlchemy import Session,update_model
from sqlalchemy.sql import and_,or_, desc
from .models import Book, BookSL, UserSL
from .tasks import syncBatchBooks
from shared.utils import printError, DEFAULT_ENCODE

from .DocConvert import DocConverter
import datetime,os, json
import uuid

import subprocess 

import jieba
    


from haystack.forms import SearchForm, ModelSearchForm
from haystack.query import SearchQuerySet
from haystack.inputs import AutoQuery, Exact, Clean
from haystack.views import SearchView, search_view_factory


session = Session()

class BookSearchView(SearchView):
    def extra_context(self):
        extra = super(BookSearchView, self).extra_context()
        #extra['top_tags'] = Tag.objects.all().annotate(num_items=Count('doubanmovie')).order_by('-num_items')[0:33]
        return extra
        
    def create_response(self):
        """
        Generates the actual HttpResponse to send back to the user.
        """
        (paginator, page) = self.build_page()
        print self.form.keywords

        context = {
            'query': self.query,
            'form': self.form,
            'page': page,
            'paginator': paginator,
            'suggestion': None,
            'keywords' : " ".join(self.form.keywords)
        }

        if self.results and hasattr(self.results, 'query') and self.results.query.backend.include_spelling:
            context['suggestion'] = self.form.get_suggestion()

        context.update(self.extra_context())
        return render_to_response(self.template, context, context_instance=self.context_class(self.request))        

class BookSearchForm(SearchForm):
    def get_result_id(self, id):
        return id
        
    def __init__(self, *args, **kwargs):
        super(BookSearchForm, self).__init__(*args, **kwargs)
        self.keywords = []

        
    def search(self):
        print 'test............'
        if not self.is_valid():
            print 'is not valid............'
            return self.no_query_found()
        if not  self.cleaned_data.get('q'):
            print 'no cleaned data............'
            #return self.no_query_found()
        '''
        print 'search in form:', self.cleaned_data['q']
        #return super(BookSearchForm, self).search()
        return self.searchqueryset.filter_or(content=self.cleaned_data['q'])
        '''
        
        query = self.cleaned_data['q']

        sqs = self.searchqueryset.filter(content=query) # actually I have one more field here...
        for word in jieba.cut_for_search(query):
            sqs = sqs.filter_or(content=word)
            self.keywords.append(word)
        if self.keywords.count(query) <=0:
            self.keywords.insert(0, query)
        
        return sqs
        
class LoginForm(forms.Form):
    account = forms.CharField(label=u'账号',required = True, max_length=200,error_messages = {
           'required': u'账号不能为空',}
            )
    password = forms.CharField(label=u'密码',required = True, max_length=200,error_messages = {
           'required': u'密码不能为空',}
            )

class Any:
    pass

    
def login(request, path):
    error = ''
    refer = path.strip()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
                try:
                    data = session.query(UserSL).filter(
                        and_(
                            UserSL.account == form.cleaned_data['account'],
                            UserSL.password == form.cleaned_data['password'],
                          )
                    ).all()[:2]
                    if len(data) > 1:
                        error = u'内部错误,请联系管理员'
                    elif len(data) != 1:
                        error = u'错误的账号或密码'
                    else:    
                        data = data[0]
                        request.session['user'] = data.account
                        request.session['userid'] = data.id
                        request.session['userkey'] = data.userid
                        request.session['admin'] = 1 if data.flag ==1 else 0
                        
                        if refer == '':
                            if str(request.session['admin']) == "1":
                                return redirect('doc_manage_index')       
                            return redirect('user_myfavorite')
                        else:    
                            return redirect('refer')
                except Exception,e:
                    error = u"登陆时发生内部错误.请联系管理员"
                    session.rollback()
                    printError()
        else:
            field, info = form.errors.items()[0]
            error = info.as_text()
            
    else:
        if request.session.get('user', '') !='' and request.session.get('userid', '') !='' and request.session.get('userkey', '') !='' and request.session.get('admin', '') != '':
            if str(request.session['admin']) == "1":
                return redirect('doc_manage_index')    
            else:
                return redirect("user_myfavorite")
        else:
            form = LoginForm()
    #return render(request, 'login.html', {'error' : error, 'refer':refer, 'menudata': "" })    
    return render_to_response('login.html', {'error' : error, 'refer':refer }, context_instance=RequestContext(request) )    
        
def logout(request):
    request.session.clear()        
    return HttpResponseRedirect('/')
    
def index(request):
    try:
        topdata = session.query(BookSL).filter(
            and_(
              )).order_by(desc(BookSL.id)).all()[:5]
    except Exception,e:
        session.rollback()
        printError()    
        
    try:
        data = session.query(BookSL).filter(
            and_(
              )).order_by(desc(BookSL.counter)).all()[:20]
    except Exception,e:
        error = u"登陆时发生内部错误.请联系管理员"
        session.rollback()
        printError()          
    return render_to_response('index.html', {'data' : data, 'topdata': topdata }, context_instance=RequestContext(request) )    
    
def viewhistory(request):
    helper = {}
    result = []
    viewed = request.session.get('history', [])    
    for item in viewed:
        if not helper.has_key(item):
            helper[item] =1
            result.append(item)
    print result 
    try:
        data = session.query(BookSL).filter(
            and_(
                BookSL.bookid.in_(result[-20:]), 
              ))
    except Exception,e:
        session.rollback()
        printError()        
    return render_to_response('history.html', {'data' : data, }, context_instance=RequestContext(request) )   
        
    
    
def getbook(bookid):
    try:
        data = session.query(BookSL).filter(
            and_(
                BookSL.bookid == bookid, 
              )).order_by(desc(BookSL.id)).first()
    except Exception,e:
        session.rollback()
        printError()        
    return data            

def view(request, bookid):
    data = getbook(bookid)
    if data == None:       
        return render_to_response('info.html', { 'title' : u'错误', 'error': u'数据库错误，请联系管理员' } , context_instance=RequestContext(request) )    
    path = data.path                
    fullapth = os.path.join(settings.BOOK_BASE, path)
    f = os.path.basename(path)
    sufix = os.path.splitext(path)[1][1:].lower()
    
    converter = DocConverter(settings.BOOK_BASE, settings.BOOK_OUTPUT_BASE,settings.BASE_DIR, printError)
    if  request.META['HTTP_USER_AGENT'].find('MSIE') >=0 or sufix == 'swf':
        html = 's_viewswf.html'
        
        if not os.path.isfile( converter.getSwfFilepath(fullapth) ):
            return render_to_response('info.html', { 'title' : u'提示', 'error': u'对不起,文档还未处理完毕，请耐心等待.' } , context_instance=RequestContext(request) )   
    else:
        ###pdf       
        #html = 's_viewpdf.html' 
        #if not os.path.isfile( converter.getPdfFilepath(fullapth) ):
        #    return render_to_response('info.html', { 'title' : u'提示', 'error': u'对不起,文档还未处理完毕，请耐心等待.' } , context_instance=RequestContext(request) )   

        ###pdf       
        html = 's_viewhtml.html' 
        if not os.path.isfile( converter.getPngFilepath(fullapth) ):
            return render_to_response('info.html', { 'title' : u'提示', 'error': u'对不起,文档还未处理完毕，请耐心等待.' } , context_instance=RequestContext(request) )   
                
    any = Any()
    any.name = f
    any.abpath = r"/" + path
    any.bookid= data.bookid
    any.size = os.path.getsize(fullapth)
    any.time = os.path.getctime(fullapth)
                
    return render_to_response(html, { 'file' : any, } , context_instance=RequestContext(request) )    
        
def directview(request, path):
    fullapth = os.path.join(settings.BOOK_BASE, path)
    f = os.path.basename(path)
    sufix = os.path.splitext(path)[1][1:].lower()
    any = Any()
    any.name = f
    any.abpath = r"/" + path
    any.fullpath= fullapth
    any.size = os.path.getsize(fullapth)
    any.time = os.path.getctime(fullapth)
    print request.META['HTTP_USER_AGENT']
    
    if  request.META['HTTP_USER_AGENT'].find('MSIE') >=0 or sufix == 'swf':
        html = 's_viewswf.html'
        #return render(request, 's_viewswf.html', { 'file' : any, } )
    else:       
        #html = 's_viewpdf.html' 
        html = 's_viewhtml.html' 
        #return render(request, 's_viewpdf.html', { 'file' : any, } )
    return render_to_response(html, { 'file' : any, } , context_instance=RequestContext(request) )    
        
def getswf(request,bookid):
    data = getbook(bookid)

django/WebDocViewer/testsite/apps/docview/templates/bookList.html
{% extends "base.html" %}

{% block header %}
 <script type="text/javascript" language="javascript">    

</script>
{% endblock %}

{% block container %}
    <div class="container">
  
  

    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">
            <form class="form-horizontal" role="form" action="." method="POST" {% if form.is_multipart %}enctype="multipart/form-data"{% endif %}>{% csrf_token %}
              <div class="form-group">
                <label for="id_search" class="col-sm-2 control-label">输入搜索条件:</label>
                <div class="col-sm-6">
                    <input id="search"  name="search" type="text" class="form-control" placeholder="书名或者作者信息" 
                    value ="{{ form.search.value|default:""|safe }}" />
                </div>
                 <div class="col-sm-2">
                    <input type="submit" class="btn btn-default" value="查 找" />
                 </div>   
              </div>
            </form>
      </div>
    </div>
       
    <div class="row">
        
      <div class="col-sm-8 col-sm-offset-2">
      <a href="/docview/manage/upload/" class="btn btn-primary active" role="button">上传新书</a>
          <table class="table table-condensed">
                <thead>
                  <tr>
                    <th>文档名</th>
                    <th>作者</th>
                    <th>分值</th>
                    <th>时间</th>
                    <th>修改</th>
                  </tr>
                </thead>
                <tbody>
                    {% for item in data %}
                  <tr>
                    <td>{{ item.name }}</td>
                    <td>{{ item.author }}</td>
                    <td>{{ item.cost }}</td>
                    <td>{{ item.uploadtime }}</td>
                    <td><a  class="btn btn-primary btn-md active" role="button" href="/docview/manage/bookedit/{{ item.id }}/" >修改</a></td>
                    <td><a  class="btn btn-primary btn-md active" role="button" href="/docview/manage/bookdelete/{{ item.id }}/" >删除</a></td>
                  </tr>
                    {% endfor %}
                </tbody>            
          </table>       
      </div>
    </div>            
        
    </div>        

{% endblock %}

{% block footer %}
  

  
{% endblock %}

django/WebDocViewer/testsite/apps/docview/templates/classview.html
{% extends "manageBase.html" %}
{% block header %}

{% endblock %}

{% block region %}
    <div class="container">

        <ol class="breadcrumb  visible-lg visible-md">
          <li><a href="/">首页</a></li>
          <li><a href=".">文档</a></li>
        </ol>        
        
      <!-- Main component for a primary marketing message or call to action -->
        
        <div class="row">
              {% for book  in data %}
                        <div class="panel panel-collapse col-md-6 col-xs-12">
        
                                <div class="col-xs-3 col-md-3">
                                    <a href="{% url 'doc_view' book.bookid %}" class="thumbnail">
                                      <img src="{{ book.getImage }}" alt="...">
                                    </a>
                                </div>    
                                
                                <div class="list-group col-xs-9 col-md-9">
                                  <a href="{% url 'doc_view' book.bookid %}" class="list-group-item ">
                                    <p  class="list-group-item-text">
                                       <strong>
                                        {{ book.name }}
                                        </strong>
                                    </p>     
                                    <p  class="list-group-item-text">
                                        
                                        {{ book.author|default:"作者:未知"  }}
                                        
                                    </p>                            
                                    <p class="list-group-item-text">
                                        
                                         {% if book.descr %}    
                                           {{ book.descr|truncatechars:20 }}
                                         {% else %}
                                            {{ book.summary|truncatechars:20 }}
                                         {% endif %}
                                        
                                    </p>                                 
                                  </a>
                                </div>
                        </div>              
                        
        
                        {% if forloop.counter|divisibleby:"2" %}
                            <div class="clearfix hidden-xs"></div>
                        {% endif %}
             {% empty %}
                <div class="col-sm-offset-2">
                    <span class="label label-success">抱歉,该类别下未收录任何文档</span>    
                </div>                                           
             {% endfor %}
             
                </div>

    </div> <!-- /container -->
{% endblock %}

django/WebDocViewer/testsite/apps/docview/templates/history.html
{% extends "manageBase.html" %}
{% load highlight %}

{% block header %}

{% endblock %}

{% block region %}
    <div class="container">
        <ol class="breadcrumb visible-lg visible-md">
          <li><a href="/">首页</a></li>
          <li><a href=".">曾经看过</a></li>
        </ol>  
      <!-- Main component for a primary marketing message or call to action -->
                <div class="panel">
                    <span class="label label-info">曾经看过...</span>
                </div>                
                
                <div class="panel panel-collapse">
                
                    {% for book  in data %}
                        <div class="list-group">
                          <a href="/docview/view/{{ book.bookid }}/" class="list-group-item ">
                            <p  class="list-group-item-text">
                               <strong><small>
                            {{ book.name }}
                                </small></strong>
                            </p>                              
                            <p  class="list-group-item-text">
                                <small>
                                {{ book.author|default:"作者:未知"  }}
                                </small>
                            </p>                            
                            <p class="list-group-item-text">
                                <small>
                                 {% if book.descr %}    
                                   {{ book.descr|truncatechars:20 }}
                                 {% else %}
                                    {{ book.summary|truncatechars:20 }}
                                 {% endif %}
                                </small>
                            </p>                                                         
                          </a>
                        </div>
                    {% endfor %}                                            
                </div>

            
    </div> <!-- /container -->
{% endblock %}

{% block footer %}
<script type="text/javascript"> 

</script>
{% endblock %}

django/WebDocViewer/testsite/apps/docview/templates/login.html
{% extends "normal.html" %}

{% block header %}
<style>
 
</style>    
 <script type="text/javascript" language="javascript">    

</script>
{% endblock %}

{% block container %}


    <div class="container">
        <ol class="breadcrumb  visible-lg visible-md">
          <li><a href="/">首页</a></li>
          <li><a href=".">登陆</a></li>
        </ol>        
        
        
        <div class="row">
            <a type="button" class="btn btn-info pull-right col-sm-1 " href="/docview/user/register/" >免费注册</a>
        </div>
        
        <div class="row">
          <div class="col-sm-4 col-sm-offset-4">
                {% if error %}
                <div class="alert alert-danger col-sm-offset-2">
                <strong>{{ error }}</strong>
                </div>
                {% endif %}
              <form class="form-horizontal" role="form" action="." method="POST" {% if form.is_multipart %}enctype="multipart/form-data"{% endif %}>{% csrf_token %}
                  <div class="form-group">
                     <label for="id_account" class="col-sm-2 control-label">账号</label>
                     <div class="col-sm-10">
                        <input id="account" name="account" type="text" class="form-control" placeholder="账号" />
                     </div>                          
                  </div>                

                  <div class="form-group">
                    <label for="id_password" class="col-sm-2 control-label">密码</label>
                     <div class="col-sm-10">
                         <input id="password" name="password" type="password" class="form-control" placeholder="密码" />
                     </div>                          
                  </div>                
                
                  <div class="form-group">
                    <div class=" col-sm-offset-2 col-sm-10">
                        <input type="submit" class="btn btn-primary btn-lg" value="登 陆" />
                    </div>
                  </div>                
                  <input type="hidden" name="refer" value="{{ refer }}" />
              </form>                        
           
          </div>
        </div>
        
    </div>        

{% endblock %}

{% block footer %}
  

  
{% endblock %}

django/WebDocViewer/testsite/apps/docview/templates/manageBase.html
{% extends "normal.html" %}

{% block header %}
 <script type="text/javascript" language="javascript">    

</script>
{% endblock %}

{% block container %}
    <div class="container">
            <div class="container">
    {% block region %}
      
    {% endblock %}        
            </div>
            
{% include "navbar.html" %}            
    </div>

{% endblock %}

{% block footer %}
  
{% endblock %}

django/WebDocViewer/testsite/apps/docview/templates/pdfviewer.html
<html dir="ltr" lang="utf-8">
    <head>
        <!-- If you want to use custom CSS (@font-face rules, for example) you should uncomment
             the following reference and use a local.css file for that. See the example.local.css
             file for a sample.
        <link rel="stylesheet" type="text/css" href="local.css" media="screen"/>
        -->

        <link rel="stylesheet" type="text/css" href="/static/Viewer.js/viewer.css" media="screen"/>
        <script src="/static/Viewer.js/viewer.js" type="text/javascript" charset="utf-8"></script>
        <script src="/static/Viewer.js/PluginLoader.js" type="text/javascript" charset="utf-8"></script>
        <script>
            console.log(window.location);
            loadDocument(window.location.hash);
        </script>
    </head>

    <body>
        <div id = "viewer">
            <div id = "titlebar">
                <div id = "documentName"></div>
                <div id = "toolbarRight">
                    <button id = "presentation" class = "toolbarButton presentation" title = "Presentation"></button>
                    <button id = "fullscreen" class = "toolbarButton fullscreen" title = "Fullscreen"></button>
                    <button id = "download" class = "toolbarButton download" title = "Download"></button>
                </div>
           </div>
            <div id = "toolbarContainer">
                <div id = "toolbar">
                    <div id = "toolbarLeft">
                        <div id = "navButtons" class = "splitToolbarButton">
                            <button id = "previous" class = "toolbarButton pageUp" title = "Previous Page"></button>
                            <div class="splitToolbarButtonSeparator"></div>
                            <button id = "next" class = "toolbarButton pageDown" title = "Next Page"></button>
                        </div>
                        <label id = "pageNumberLabel" class = "toolbarLabel" for = "pageNumber">Page:</label>
                        <input type = "number" id = "pageNumber" class = "toolbarField pageNumber"></input>
                        <span id = "numPages" class = "toolbarLabel"></span>
                    </div>
                    <div id = "toolbarMiddleContainer" class = "outerCenter">
                        <div id = "toolbarMiddle" class = "innerCenter">
                            <div id = 'zoomButtons' class = "splitToolbarButton">
                                <button id = "zoomOut" class = "toolbarButton zoomOut" title = "Zoom Out"></button>
                                <div class="splitToolbarButtonSeparator"></div>
                                <button id = "zoomIn" class = "toolbarButton zoomIn" title = "Zoom In"></button>
                            </div>
                            <span id="scaleSelectContainer" class="dropdownToolbarButton">
                                <select id="scaleSelect" title="Zoom" oncontextmenu="return false;">
                                    <option id="pageAutoOption" value="auto" selected>Automatic</option>
                                    <option id="pageActualOption" value="page-actual">Actual Size</option>
                                    <option id="pageWidthOption" value="page-width">Full Width</option>
                                    <option id="customScaleOption" value="custom"></option>
                                    <option value="0.5">50%</option>
                                    <option value="0.75">75%</option>
                                    <option value="1">100%</option>
                                    <option value="1.25">125%</option>
                                    <option value="1.5">150%</option>
                                    <option value="2">200%</option>
                                </select>
                            </span>
                            <div id = "sliderContainer">
                                <div id = "slider"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id = "canvasContainer">
                <div id = "canvas"></div>
            </div>
            <div id = "overlayNavigator">
                <div id = "previousPage"></div>
                <div id = "nextPage"></div>
            </div>
            <div id = "overlayCloseButton">
            &#10006;
            </div>
        </div>
    </body>
</html>